# ===================================================================
# Mol-Dorm 项目公共基础配置文件 (Pig 风格抽离)
# 包含：数据库、Redis(带密码)、MyBatis-Plus、Sa-Token 基础设定
# ===================================================================

spring:
  # 1. 数据库连接池通用配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: 注意 serverTimezone 必须指定，否则 Java 写入时间可能与数据库差 8 小时
    url: jdbc:mysql://localhost:3306/mol-dorm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456              # 请在此处填入你的 MySQL 密码
    hikari:
      minimum-idle: 5             # 最小空闲连接数
      maximum-pool-size: 20       # 最大连接池数量
      idle-timeout: 30000         # 连接空闲超时时间（毫秒）
      connection-timeout: 30000   # 等待连接池分配连接的最大时长

  # 2. Redis 核心配置
  data:
    redis:
      host: localhost             # Redis 服务器地址
      port: 6379                  # Redis 端口
      password: a1b2c3            # 在这里填入你的本地 Redis 密码
      database: 0                 # 使用 0 号数据库
      timeout: 5000ms             # 连接超时时间
      lettuce:
        pool:
          max-active: 20          # 最大并发连接数
          max-idle: 10            # 最大空闲连接
          min-idle: 2             # 最小空闲连接

  # 3. 全局 JSON 序列化配置 (Jackson)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 前端接收到的日期格式
    time-zone: GMT+8                # 强制使用东八区时间

# ===================================================================
# MyBatis-Plus 全局配置
# ===================================================================
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id          # 主键策略：自动分配雪花算法 ID (适合分布式)
      logic-delete-field: delFlag # 全局逻辑删除字段名 (对应 BaseEntity 中的 delFlag)
      logic-delete-value: 1       # 逻辑值：已删除为 1
      logic-not-delete-value: 0    # 逻辑值：正常存活为 0
  configuration:
    map-underscore-to-camel-case: true # 自动开启驼峰命名转换 (数据库 a_column -> 实体类 aColumn)
    cache-enabled: false               # 禁用 MyBatis 一级缓存，避免分布式环境下产生脏数据

# ===================================================================
# Sa-Token 权限基础配置
# ===================================================================
sa-token:
  token-name: mol-token           # Token 在 Header 或 Cookie 中的键名
  timeout: 2592000                # Token 有效期 (单位:秒，此处为30天)
  active-timeout: -1              # 临时有效期 (即：多长时间无操作就过期)，-1 表示不开启
  is-share: true                  # 是否允许账号多地同时登录
  token-style: uuid               # Token 生成风格：UUID
  is-print: true                  # 启动时是否在控制台打印 Sa-Token 字符画
  is-log: false                   # 是否在控制台打印 Sa-Token 的内部操作日志

# ===================================================================
# Knife4j 4.x 公共 UI 增强配置
# ===================================================================
knife4j:
  enable: true            # 开启 Knife4j 增强 UI 界面 (doc.html)
  setting:
    language: zh_cn       # 界面语言：中文
    enable-swagger-models: true   # 界面显示文档模型
    enable-reload-cache-parameter: true   # 允许在界面刷新时保留参数缓存